name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Check for package.json
        run: |
          if [ -f "package.json" ]; then
            echo "package.json exists"
          else
            echo "package.json does not exist"
            exit 1
          fi

      - name: Preferred package manager detection
        id: detect-package-manager
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "::set-output name=manager::pnpm"
            echo "::set-output name=command::install"
          elif [ -f "yarn.lock" ]; then
            echo "::set-output name=manager::yarn"
            echo "::set-output name=command::install"
          elif [ -f "package-lock.json" ]; then
            echo "::set-output name=manager::npm"
            echo "::set-output name=command::ci"
          else
            echo "::set-output name=manager::npm"
            echo "::set-output name=command::install"
          fi

      - name: Install dependencies
        run: |
          if [ "${{ steps.detect-package-manager.outputs.manager }}" = "pnpm" ]; then
            npm install -g pnpm
            pnpm install
          elif [ "${{ steps.detect-package-manager.outputs.manager }}" = "yarn" ]; then
            yarn install
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: List output directory
        run: ls -la ./out || echo "Output directory not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com' 